<?php

acf_add_local_field_group(
    [
        'key' => 'group_block_cloud-tags',
        'title' => __("Bloc : Nuage d'étiquettes", 'hmb-blocks'),
        'fields' => [
            [
                'key' => 'group_block_cloud-tags__wrapper',
                'label' => __("Liste d'étiquettes", 'hmb-blocks'),
                'name' => 'tags-list',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'layout' => 'table',
                'pagination' => 0,
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => __('Ajouter un élément', 'hmb-blocks'),
                'rows_per_page' => 20,
                'sub_fields' => [
                    [
                        'key' => 'group_block_cloud-tags__title',
                        'label' => __('Titre', 'hmb-blocks'),
                        'name' => 'title',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'group_block_cloud-tags__wrapper',
                    ],
                    [
                        'key' => 'group_block_cloud-tags__level',
                        'label' => __('Importance', 'hmb-blocks'),
                        'name' => 'level',
                        'aria-label' => '',
                        'type' => 'range',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => 8,
                        'min' => 1,
                        'max' => 8,
                        'step' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'group_block_cloud-tags__wrapper',
                    ],
                ],
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'hmb/cloud-tags',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ]
);

