#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
blue='\033[0;34m'
no_color='\033[0m'

echo -e ""
echo -e "${red}ε=ε=ε=┌( >_<)┘ ❗Les fichiers compilés de ce projet ne sont pas versionnés, un npm run prod est peut-être nécessaire ❗ε=ε=ε=┌( >_<)┘${no_color}"
