#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
blue='\033[0;34m'
no_color='\033[0m'

echo ""
echo -e "${green}～(´･ω･｀～)(～´･ω･｀)～ Commit réussi ! ～(´･ω･｀～)(～´･ω･｀)～${no_color}"
echo ""
